### ISSUE TITLE
コマンドラインオプションなしでの実行のヘルプメニュー出力

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/RustyBlue#27]
コマンドラインオプションなしで実行したら、何も出力されないので、その場合は-hと同じようにヘルプメニューを出したいです。

**Comment by hitenkoku** [comment]
ヘルプメニューの出力はできるか検討中の段階ではありますが何も入力しなければ以下のようにエラーを返すようにするところまで実装できましたがこちらではいかがでしょうか

> PS <Folder>\RustyBlue> .\rusty_blue.exe   
> error: The following required arguments were not provided:
>     <--filepath <FILEPATH>|--dirpath <DIRECTORYPATH>|--credits>
> 
> USAGE:
>     rusty_blue.exe [OPTIONS] <--filepath <FILEPATH>|--dirpath <DIRECTORYPATH>|--credits>
> 
> For more information try --help

**Comment by hitenkoku** [comment]
https://github.com/hitenkoku/RustyBlue/commit/a550e6f41d03c1153ce76231ff847c5b661537fe のやり方だとtest codeがerrorでおちる。requiredが原因であることが判明した
