### ISSUE TITLE
ディレクトリスキャンする時に不要な出力が多い

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/RustyBlue#30]
ディレクトリをスキャンする場合、何も検知されなくてもファイル名が出力されて、結果がどこにあるのか分かりにくくなるので、ファイル名と------------------を出力しないようにしたいです。
例：
---------------------
C:\Windows\System32\winevt\logs\AMSI%4Operational.evtx
---------------------
---------------------
C:\Windows\System32\winevt\logs\Application.evtx
---------------------
---------------------
C:\Windows\System32\winevt\logs\HardwareEvents.evtx
---------------------
---------------------
C:\Windows\System32\winevt\logs\Internet Explorer.evtx
---------------------
---------------------
C:\Windows\System32\winevt\logs\Key Management Service.evtx
---------------------
---------------------
C:\Windows\System32\winevt\logs\Microsoft-AppV-Client%4Admin.evtx
---------------------
---------------------
C:\Windows\System32\winevt\logs\Microsoft-AppV-Client%4Operational.evtx
---------------------
---------------------
C:\Windows\System32\winevt\logs\Microsoft-AppV-Client%4Virtual Applications.evtx

**Comment by hitenkoku** [comment]
私の方で対応しておきます。アサイン権限がないのでコメントで返しておきます

**Comment by hitenkoku** [comment]
@YamatoSecurity 確認してみましたがすべてに適用するのはそれなりに手間がかかる気がしています。

applockerなどで検知される各関数では検知されないところでも出力関数は利用しており、基本は末端では検知した情報をため込んで最後に出力という形になっており対処することは容易なのですが、Security.rsは複数の検知関数を順番に実施しており、どこで最初の検知をしたかというのを追うというのが難しくなります。※最初の検知の時のみファイルパスを出力するという手順にしないとSecurityの各検知関数で検知されたらファイル名を出力するという冗長な作りになる。

別issueで挙げられているcsv出力も考慮すると各検知のメソッドまでファイルパス情報を引き渡す必要が出てくるかなと考えています。
