### ISSUE TITLE
"Sensitive" Typo

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/RustyBlue#31]
Message: Sensititive Privilege Use Exceeds ThresholdのSensititiveはtypoで「Sensitive」が正しいです。
(元々DeepblueCliのtypoです）

**Comment by hitenkoku** [comment]
私の方で対応しておきます。アサイン権限がないのでコメントで返しておきます

**Comment by hitenkoku** [comment]
他の課題項目が重いのでまず軽いこちらをさっさとPull Requestだしておきます
